name: bokeh_stream
channels:
    - bokeh
    - memex
dependencies:
    - bokeh=0.10.0
    - python=2.7.8
    - pytest=2.8.1
    - elasticnutch>=1.11
    - pip:
        - kombu
        - supervisor
        - git+https://github.com/memex-explorer/nutch-python